# Generated by Django 5.2.4 on 2026-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_skillmatch_created_at_alter_userprofile_skills_have_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
