"""
Django settings for SkillSwap project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os


from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES
# ============================================================

load_dotenv(BASE_DIR / '.env')


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv(
    'DEBUG',
    'False'
).lower() == 'true'

ALLOWED_HOSTS = []


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # --------------------------------------------------------
    # Django apps
    # --------------------------------------------------------
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',

    # --------------------------------------------------------
    # Third-party apps
    # --------------------------------------------------------

    'rest_framework',
    'channels',

    # --------------------------------------------------------
    # Your applications
    # --------------------------------------------------------

    'myapp',
    

    # --------------------------------------------------------
    # Django Allauth
    # --------------------------------------------------------

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]
ASGI_APPLICATION = 'SkillSwap.asgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    },
}

# ============================================================
# ASGI / CHANNELS
# ============================================================


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                ('127.0.0.1', 6379)
            ],
        },
    },
}


# ============================================================
# DJANGO SITES
# ============================================================

SITE_ID = 1


# ============================================================
# AUTHENTICATION
# ============================================================

AUTHENTICATION_BACKENDS = [

    # Normal Django username/password authentication
    'django.contrib.auth.backends.ModelBackend',

    # Django Allauth authentication
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Login page
LOGIN_URL = 'login'


# Where normal login redirects
LOGIN_REDIRECT_URL = 'home'


# Where logout redirects
LOGOUT_REDIRECT_URL = 'home'


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.'
        'JWTAuthentication',

    ),

    'DEFAULT_PERMISSION_CLASSES': (

        'rest_framework.permissions.IsAuthenticated',

    ),
}


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'allauth.account.middleware.AccountMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = 'SkillSwap.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [

    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'SkillSwap.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

DATABASES = {

    'default': {

        'ENGINE':
            'django.db.backends.postgresql',

        'NAME':
            os.getenv('DB_NAME'),

        'USER':
            os.getenv('DB_USER'),

        'PASSWORD':
            os.getenv('DB_PASSWORD'),

        'HOST':
            os.getenv(
                'DB_HOST',
                'localhost'
            ),

        'PORT':
            os.getenv(
                'DB_PORT',
                '5432'
            ),
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator',
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# LOGGING
# ============================================================

LOGGING = {

    'version': 1,

    'disable_existing_loggers': False,

    'formatters': {

        'websocket': {

            'format':
                '{asctime} {levelname} {message}',

            'style': '{',

        },
    },

    'handlers': {

        'websocket_file': {

            'class':
                'logging.FileHandler',

            'filename':
                BASE_DIR / 'websocket.log',

            'formatter':
                'websocket',

        },
    },

    'loggers': {

        'websocket': {

            'handlers': [
                'websocket_file'
            ],

            'level': 'INFO',

            'propagate': False,

        },
    },
}

Q_CLUSTER = {
    'name': 'SkillSwap',
    'workers': 1,
    'timeout': 60,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 1,
    'orm': 'default',
    'cpu_affinity': 1,
}